---
title: "mb5370-module-4-report"
author: "Carolina Freitas"
date: '2023-05-03'
output: html_document
---


## QFISH Data Report####

```{r}
#Importing QFish data
library (readr)
initial_data <- read.csv("data/sharkcontrol.csv")
```

```{r}
#Ensures every blank space is identified as a blank space

initial_data <- as.data.frame(lapply(initial_data, function(x) gsub("^\\s*$", "", x)))
# ^ represents the start of line
#\\s matches any white space character
#* specifies that the previous symbol "\\s" can occur zero or more times. 
#$ represents the end of line

```

# Tidying the data ####
```{r}
library(dplyr)
library(tidyr)
data_table <- setNames(initial_data, c("Area", paste(names(initial_data), unlist(initial_data[1, ], use.names = FALSE), sep = "_")[-1])) %>% 
  slice(-1) %>% #
  pivot_longer(-Area) %>% 
  separate(name, into = c("Year", "SpeciesGroup"), sep = "_")
#This section reorganises the table into Area, Year, species group and value which = catches

```


```{r}
#Remove prefix Area. and X from columns 1 and 2
data_table <- data_table %>%
  mutate(Area = sub("^Area\\.", "", Area),
         Year = sub("^X", "", Year))
```

```{r}
#Rename column from value to catches
colnames(data_table)[colnames(data_table) == "value"] <- "Catches"
```

```{r}
#Remove all rows with totals and grand totals
#install.packages("stringr")
library(stringr)

data_table <- data_table[!str_detect(data_table$Area, "Grand Total") & !str_detect(data_table$Year, "Total"), ]

```

```{r}
#Remove the suffix in the years. e.g. 2001.1 is replaced by 2001
data_table$Year <- str_remove(data_table$Year, "\\..*")
```

```{r}
#Remove all rows with blank cells
data_clean <- subset(data_table, !is.na(Catches) & nzchar(as.character(Catches)))
#subset() function is used to filter the dataframe based on the !is.na and nzchar condition.
#this condition selects the rows where the cells under the column Catches is not empty
```

# Plotting the data into a timeseries ####
```{r}
#converting catches values to numerical data
data_clean$Catches <- as.numeric(data_clean$Catches)
```

```{r}
# creating a data table for the timesereries with the columns, year, speciesgroup and catches
totals_per_year <- data_clean %>%
  group_by(Year, SpeciesGroup) %>%
  summarise(TotalCatches = sum(Catches))

# View the resulting table
print(totals_per_year)
```


```{r}
#Creates a timeseries of total catches per year for all species groups
library(ggplot2)
ggplot(totals_per_year, aes(x = Year, y = TotalCatches, color = SpeciesGroup, group = SpeciesGroup)) +
  theme_classic() +
  geom_line() +
  labs(x = "Year", y = "Total Number of Catches", color = "Species Group") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
 
```
```{r}
#Organising the data to plot number of catches per area
# Aggregate the data to calculate total catches per area and species group
totals_per_area <- aggregate(Catches ~ Area + SpeciesGroup, data = data_clean, FUN = sum)
```

```{r}
# Create the bar plot

b <-  ggplot(totals_per_area, aes(x = Area, y = Catches, fill = SpeciesGroup)) +
  theme_classic() +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Location", y = "Total Number of Catches") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + # x axis ticks at 45 degrees
  facet_wrap(~SpeciesGroup)
b + theme(legend.position = "")


```



#Data Analysis Section 2 ####
```{r}
# Since sharks account for most of the catches, we will now focus on sharks and how GBR zoning affects the number of catches. We divide the GBR into South, North, Central and Far North using the Reef Explorer page on the GBRMPA site.
library(dplyr)

shark_data <- data_clean %>%
  mutate(Area = case_when(
    Area == "Cairns" ~ "North",
    Area == "Townsville" ~ "Central",
    Area %in% c("Bundaberg", "Mackay", "Bribie Island", "Gladstone", "Gold Coast", 
                "Capricorn Coast", "Nth Stradbroke Is.", "Rainbow Beach", 
                "Sunshine Coast South", "Sunshine Coast North", "Sunshine Coast South & Bribie Island") ~ "South",
    TRUE ~ Area  
  ))
#this chunk replaces the names of the locations with its corresponding GBR sector
```


```{r}
#Creating a data table just for sharks
shark_subset <- subset(shark_data, SpeciesGroup == "Shark")

```


```{r}
#ggplot to plot barplot of shark catches per GBR sector
shark_subset$Area <- factor(shark_subset$Area, levels = c("North", "Central", "South"))
#this line changes the order of the bar plot so it shows data from north to south.

c <- ggplot(shark_subset, aes(x = Area, y = Catches)) +
  theme_classic() +
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "GBR Sector", y = "Number of Catches") +
  ggtitle("Number of Shark Catches by GBR Sector from 2001 to 2022")
  
c + theme(legend.position = "") #so legend does not appear
c + theme(plot.title = element_text(hjust = 0.5)) #makes centers title
```

